### ISSUE TITLE
[1.16.5 Forge] The specified resource "fireproofboats.mixins.json" could not be found

### ISSUE THREAD

**Issue by NighthowlerStudios** [JDKDigital/fireproofboats#1]
Causes crash on startup.  You need to make sure your mod's build and mixin settings are correct for this version.

**Comment by JaisDK** [comment]
Can you include a log please?

**Comment by NighthowlerStudios** [comment]
mixin specified resource crashes are very easy to understand, but here it is anyway....

[2023-06-10-3.log](https://github.com/JDKDigital/fireproofboats/files/11712869/2023-06-10-3.log)

**Comment by NighthowlerStudios** [comment]
all the crash is telling you is the name you told mixin your mixin.json would be at is incorrect.

**Comment by NighthowlerStudios** [comment]
https://github.com/JDKDigital/fireproofboats/blob/8a4c2ffc583f1dd85a3f246f66b7dbec790762b5/build.gradle#L110

**Comment by NighthowlerStudios** [comment]
the crash is because you put an "s" in "mixins", when it should be "mixin".  the typo causes mixin library to never see the json in your resources

**Comment by NighthowlerStudios** [comment]
I've given you the line where it's broken at.  if you need any further help spotting it I can make a pull request.  just remove the s from the typo, rebuild and publish and you should be good to go :)

**Comment by JaisDK** [comment]
Thanks I’ll get a fix out :)

**Comment by JaisDK** [comment]
it's out
